INSERT INTO muscle_types (title) VALUES ("Спина"); 
INSERT INTO muscle_types (title) VALUES ("Ноги");  
INSERT INTO muscle_types (title) VALUES ("Руки"); 
INSERT INTO muscle_types (title) VALUES ("Плечи"); 
INSERT INTO muscle_types (title) VALUES ("Грудь"); 
INSERT INTO muscle_types (title) VALUES ("Пресс");  
INSERT INTO intensity (intensity) VALUES ("Легкая");  
INSERT INTO intensity (intensity) VALUES ("Средняя");
INSERT INTO intensity (intensity) VALUES ("Тяжелая");

INSERT INTO exercises (title, type) VALUES ("Тяга верхнего блока", 1);
INSERT INTO exercises (title, type) VALUES ("Подтягивания", 1);
INSERT INTO exercises (title, type) VALUES ("Пуловер", 1);
INSERT INTO exercises (title, type) VALUES ("Тяга нижнего блока", 1);
INSERT INTO exercises (title, type) VALUES ("Становая тяга", 1);
INSERT INTO exercises (title, type) VALUES ("Тяга Т-грифа", 1);
INSERT INTO exercises (title, type) VALUES ("Тяга штанги к поясу", 1);
INSERT INTO exercises (title, type) VALUES ("Гиперэксензия", 1);
INSERT INTO exercises (title, type) VALUES ("Good Morning", 1);
INSERT INTO exercises (title, type) VALUES ("Приседания со штангой", 2);
INSERT INTO exercises (title, type) VALUES ("Болгарские выпады", 2);
INSERT INTO exercises (title, type) VALUES ("Фронтальный присед", 2);
INSERT INTO exercises (title, type) VALUES ("Разгибание ног в тренажере", 2);
INSERT INTO exercises (title, type) VALUES ("Сгибание ног в тренажере", 2);
INSERT INTO exercises (title, type) VALUES ("Выпады с гантелями", 2);
INSERT INTO exercises (title, type) VALUES ("Румынская тяга", 2);
INSERT INTO exercises (title, type) VALUES ("Махи ногой с манжетой", 2);
INSERT INTO exercises (title, type) VALUES ("Ягодичный мостик", 2);
INSERT INTO exercises (title, type) VALUES ("Подъем ног на тренажере сидя", 2);
INSERT INTO exercises (title, type) VALUES ("Подъем на носки", 2);
INSERT INTO exercises (title, type) VALUES ("Армейский жим гантелями сидя", 4);
INSERT INTO exercises (title, type) VALUES ("Тяга штанги к подбородку", 4);
INSERT INTO exercises (title, type) VALUES ("Жим штанги стоя", 4);
INSERT INTO exercises (title, type) VALUES ("Разведение гантелей в наклоне", 4);
INSERT INTO exercises (title, type) VALUES ("Отведение гантелей в стороны", 4);
INSERT INTO exercises (title, type) VALUES ("Подъем гантелей перед собой", 4);
INSERT INTO exercises (title, type) VALUES ("Жим Арнольда", 4);
INSERT INTO exercises (title, type) VALUES ("Жим штанги лежа", 5);
INSERT INTO exercises (title, type) VALUES ("Жим гантелей лежа", 5);
INSERT INTO exercises (title, type) VALUES ("Вертикальный жим", 5);
INSERT INTO exercises (title, type) VALUES ("Разводка гантелей в стороны лежа", 5);
INSERT INTO exercises (title, type) VALUES ("Жим сидя в тренажере", 5);
INSERT INTO exercises (title, type) VALUES ("Отжимания на брусьях", 5);
INSERT INTO exercises (title, type) VALUES ("Сведение рук в кроссовере", 5);
INSERT INTO exercises (title, type) VALUES ("Подъем штанги на бицепс стоя", 3);
INSERT INTO exercises (title, type) VALUES ("Подъем гантелей с супинацией", 3);
INSERT INTO exercises (title, type) VALUES ("Подъем гантелей сидя с упором на бедро", 3);
INSERT INTO exercises (title, type) VALUES ("Молотки", 3);
INSERT INTO exercises (title, type) VALUES ("Французский жим", 3);
INSERT INTO exercises (title, type) VALUES ("Жим лежа узким хватом", 3);
INSERT INTO exercises (title, type) VALUES ("Разгибание руки с гантелью из-за головы", 3);
INSERT INTO exercises (title, type) VALUES ("Разгибание рук в верхнем блоке", 3);
INSERT INTO exercises (title, type) VALUES ("Велосипед", 6);
INSERT INTO exercises (title, type) VALUES ("Ножницы", 6);
INSERT INTO exercises (title, type) VALUES ("Скручивания", 6);
INSERT INTO exercises (title, type) VALUES ("Планка", 6);
