INSERT INTO muscle_types (title) VALUES ("Спина"); 
INSERT INTO muscle_types (title) VALUES ("Ноги");  
INSERT INTO muscle_types (title) VALUES ("Руки"); 
INSERT INTO muscle_types (title) VALUES ("Плечи"); 
INSERT INTO muscle_types (title) VALUES ("Грудь"); 
INSERT INTO muscle_types (title) VALUES ("Пресс"); 

INSERT INTO intensity (intensity) VALUES ("Легкая");  
INSERT INTO intensity (intensity) VALUES ("Средняя");
INSERT INTO intensity (intensity) VALUES ("Тяжелая");

INSERT INTO exercises (title, type) VALUES ("Тяга верхнего блока", 1);
INSERT INTO exercises (title, type) VALUES ("Подтягивания", 1);
INSERT INTO exercises (title, type) VALUES ("Пуловер", 1);
INSERT INTO exercises (title, type) VALUES ("Тяга нижнего блока", 1);
INSERT INTO exercises (title, type) VALUES ("Становая тяга", 1);
INSERT INTO exercises (title, type) VALUES ("Тяга Т-грифа", 1);
INSERT INTO exercises (title, type) VALUES ("Тяга штанги к поясу", 1);
INSERT INTO exercises (title, type) VALUES ("Гиперэксензия", 1);
INSERT INTO exercises (title, type) VALUES ("Good Morning", 1);
INSERT INTO exercises (title, type) VALUES ("Приседания со штангой", 2);
INSERT INTO exercises (title, type) VALUES ("Болгарские выпады", 2);
INSERT INTO exercises (title, type) VALUES ("Фронтальный присед", 2);
INSERT INTO exercises (title, type) VALUES ("Разгибание ног в тренажере", 2);
INSERT INTO exercises (title, type) VALUES ("Сгибание ног в тренажере", 2);
INSERT INTO exercises (title, type) VALUES ("Выпады с гантелями", 2);
INSERT INTO exercises (title, type) VALUES ("Румынская тяга", 2);
INSERT INTO exercises (title, type) VALUES ("Махи ногой с манжетой", 2);
INSERT INTO exercises (title, type) VALUES ("Ягодичный мостик", 2);
INSERT INTO exercises (title, type) VALUES ("Подъем ног на тренажере сидя", 2);
INSERT INTO exercises (title, type) VALUES ("Подъем на носки", 2);
INSERT INTO exercises (title, type) VALUES ("Армейский жим гантелями сидя", 4);
INSERT INTO exercises (title, type) VALUES ("Тяга штанги к подбородку", 4);
INSERT INTO exercises (title, type) VALUES ("Жим штанги стоя", 4);
INSERT INTO exercises (title, type) VALUES ("Разведение гантелей в наклоне", 4);
INSERT INTO exercises (title, type) VALUES ("Отведение гантелей в стороны", 4);
INSERT INTO exercises (title, type) VALUES ("Подъем гантелей перед собой", 4);
INSERT INTO exercises (title, type) VALUES ("Жим Арнольда", 4);
INSERT INTO exercises (title, type) VALUES ("Жим штанги лежа", 5);
INSERT INTO exercises (title, type) VALUES ("Жим гантелей лежа", 5);
INSERT INTO exercises (title, type) VALUES ("Вертикальный жим", 5);
INSERT INTO exercises (title, type) VALUES ("Разводка гантелей в стороны лежа", 5);
INSERT INTO exercises (title, type) VALUES ("Жим сидя в тренажере", 5);
INSERT INTO exercises (title, type) VALUES ("Отжимания на брусьях", 5);
INSERT INTO exercises (title, type) VALUES ("Сведение рук в кроссовере", 5);
INSERT INTO exercises (title, type) VALUES ("Подъем штанги на бицепс стоя", 3);
INSERT INTO exercises (title, type) VALUES ("Подъем гантелей с супинацией", 3);
INSERT INTO exercises (title, type) VALUES ("Подъем гантелей сидя с упором на бедро", 3);
INSERT INTO exercises (title, type) VALUES ("Молотки", 3);
INSERT INTO exercises (title, type) VALUES ("Французский жим", 3);
INSERT INTO exercises (title, type) VALUES ("Жим лежа узким хватом", 3);
INSERT INTO exercises (title, type) VALUES ("Разгибание руки с гантелью из-за головы", 3);
INSERT INTO exercises (title, type) VALUES ("Разгибание рук в верхнем блоке", 3);
INSERT INTO exercises (title, type) VALUES ("Велосипед", 6);
INSERT INTO exercises (title, type) VALUES ("Ножницы", 6);
INSERT INTO exercises (title, type) VALUES ("Скручивания", 6);
INSERT INTO exercises (title, type) VALUES ("Планка", 6);

INSERT INTO periodicity (intensity, periodicity) VALUES (1, "4x15");
INSERT INTO periodicity (intensity, periodicity) VALUES (1, "4x12");
INSERT INTO periodicity (intensity, periodicity) VALUES (1, "3x12");
INSERT INTO periodicity (intensity, periodicity) VALUES (1, "3x20");
INSERT INTO periodicity (intensity, periodicity) VALUES (2, "3x10");
INSERT INTO periodicity (intensity, periodicity) VALUES (2, "3x8");
INSERT INTO periodicity (intensity, periodicity) VALUES (2, "4x8");
INSERT INTO periodicity (intensity, periodicity) VALUES (2, "4x10");
INSERT INTO periodicity (intensity, periodicity) VALUES (2, "4x6");
INSERT INTO periodicity (intensity, periodicity) VALUES (2, "3x6");
INSERT INTO periodicity (intensity, periodicity) VALUES (3, "3x4");
INSERT INTO periodicity (intensity, periodicity) VALUES (3, "3x3");
INSERT INTO periodicity (intensity, periodicity) VALUES (3, "3x2");
INSERT INTO periodicity (intensity, periodicity) VALUES (3, "4x2");
INSERT INTO periodicity (intensity, periodicity) VALUES (3, "4x4");
INSERT INTO periodicity (intensity, periodicity) VALUES (3, "2x3");
INSERT INTO periodicity (intensity, periodicity) VALUES (3, "5x2");
INSERT INTO periodicity (intensity, periodicity) VALUES (3, "5x3");

INSERT INTO training_plans (combinations, intensity) VALUES ("Спина и бицепс", 1);
INSERT INTO training_plans (combinations, intensity) VALUES ("Спина и бицепс", 2);
INSERT INTO training_plans (combinations, intensity) VALUES ("Спина и бицепс", 3);
INSERT INTO training_plans (combinations, intensity) VALUES ("Грудь, трицепс и пресс", 1);
INSERT INTO training_plans (combinations, intensity) VALUES ("Грудь, трицепс и пресс", 2);
INSERT INTO training_plans (combinations, intensity) VALUES ("Грудь, трицепс и пресс", 3);
INSERT INTO training_plans (combinations, intensity) VALUES ("Грудь, плечи и трицепс", 1);
INSERT INTO training_plans (combinations, intensity) VALUES ("Грудь, плечи и трицепс", 2);
INSERT INTO training_plans (combinations, intensity) VALUES ("Грудь, плечи и трицепс", 3);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги, грудь и плечи", 1);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги, грудь и плечи", 2);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги, грудь и плечи", 3);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги, грудь и руки", 1);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги, грудь и руки", 2);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги, грудь и руки", 3);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги, плечи и руки", 1);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги, плечи и руки", 2);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги, плечи и руки", 3);
INSERT INTO training_plans (combinations, intensity) VALUES ("Спина, бицепс и пресс", 1);
INSERT INTO training_plans (combinations, intensity) VALUES ("Спина, бицепс и пресс", 2);
INSERT INTO training_plans (combinations, intensity) VALUES ("Спина, бицепс и пресс", 3);
INSERT INTO training_plans (combinations, intensity) VALUES ("Спина и грудь", 1);
INSERT INTO training_plans (combinations, intensity) VALUES ("Спина и грудь", 2);
INSERT INTO training_plans (combinations, intensity) VALUES ("Спина и грудь", 3);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги и спина", 1);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги и спина", 2);
INSERT INTO training_plans (combinations, intensity) VALUES ("Ноги и спина", 3);